import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../app/_components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-custBackground`}>
        <Header />
        <main className="flex flex-col items-center justify-center w-full max-w-screen-xl min-h-screen gap-4 px-10 py-24">
        {children}
        </main>
      </body>
    </html>
  );
}
